### ISSUE TITLE
How to use this tool

### ISSUE THREAD

**Issue by Apple-QAQ** [Za08/HighIQBot#1]
Hello bro~
请问这个工具如何使用~
~~什么时候release里有个正式版本啊~~
thanks~

**Comment by Za08** [comment]
查看README.md

**Comment by Za08** [comment]
> Hello bro~ 请问这个工具如何使用~ ~什么时候release里有个正式版本啊~ thanks~
查看README.md

**Comment by Apple-QAQ** [comment]
> > Hello bro~ 请问这个工具如何使用~ ~什么时候release里有个正式版本啊~ thanks~
> > 查看README.md

感谢您的回复，好工具啊！谢谢
![image](https://user-images.githubusercontent.com/88485487/149743819-39ece756-296c-4c41-a60e-4206228d9fe4.png)
